#!/bin/sh
# This is the post installation script for tor2web
if ! id -u tor2web >/dev/null 2>&1; then
  useradd tor2web -u 7331 -b /var/tor2web/ -s /bin/false
fi

if [ ! -d /var/tor2web ]; then
  mkdir -p /var/tor2web/
fi

chown tor2web:tor2web /var/tor2web
