#!/bin/sh
# This is the post installation script for tor2web
if ! id -u tor2web >/dev/null 2>&1; then
  useradd tor2web -u 7331 -b /home/tor2web -s /bin/false
fi

if [ ! -d /home/tor2web ]; then
  mkdir -p /home/tor2web
  mkdir -p /home/tor2web/certs
  mkdir -p /home/tor2web/logs
  touch /home/tor2web/logs/debug.log
  touch /home/tor2web/logs/access.log 
  chown tor2web:tor2web /home/tor2web -R
fi

#DEBHELPER#
