#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. ${DIR}/common_inc.sh

usage()
{
cat << EOF
usage: ./${SCRIPTNAME} options

OPTIONS:
   -h      Show this message
   -v      To build a tagged release
   -n      To build a non signed package
   -y      Assume 'yes' to all questions

EOF
}

SIGN=1
while getopts “yhv:n” OPTION
do
  case $OPTION in
    h)
      usage
      exit 1
      ;;
    v)
      TAG=$OPTARG
      ;;
    n)
      SIGN=0
      ;;
    y)
      AUTOYES=1
      ;;
    ?)
      usage
      exit
      ;;
    esac
done

auto_setup_env()
{
  cd ${BUILD_DIR}
  if [ -d ${T2W_TMP} ]; then
    echo "[+] Removing ${T2W_TMP}"
    rm -rf ${T2W_TMP}
  fi
  if [ -d ${T2W_DIR} ]; then
    echo "[+] Copying existent ${T2W_DIR} in ${T2W_TMP}"
    cp ${T2W_DIR} ${T2W_TMP} -r
  else
    echo "[+] Cloning T2W in ${T2W_TMP}"
    git clone $T2W_GIT_REPO ${T2W_TMP}
  fi
}

interactive_setup_env()
{
  cd ${BUILD_DIR}
  if [ -d ${T2W_TMP} ]; then
    echo "Directory ${T2W_TMP} already present and need to be removed"
    ANSWER=''
    until [[ $ANSWER = [yn] ]]; do
      read -n1 -p "Do you want to delete ${T2W_TMP}? (y/n): " ANSWER
      echo
    done
    if [[ $ANSWER != 'y' ]]; then
      echo "Cannot proceed"
      exit
    fi
    rm -rf ${T2W_TMP}
  fi
  if [ -d ${T2W_DIR} ]; then
    echo "Directory ${T2W_DIR} already present. Can be used as package source"
    ANSWER=''
    until [[ $ANSWER = [yn] ]]; do
      read -n1 -p "Do you want to use the existing repository from ${T2W_DIR} (y/n): " ANSWER
      echo
    done
    if [[ $ANSWER != 'y' ]]; then
      echo "[+] Cloning T2W in ${T2W_TMP}"
      git clone $T2W_GIT_REPO ${T2W_TMP}
    else
      echo "[+] Copying existent ${T2W_DIR} in ${T2W_TMP}"
      cp ${T2W_DIR} ${T2W_TMP} -r
      USING_EXISTENT_DIR=1
    fi
  else
    echo "[+] Cloning T2W in ${T2W_TMP}"
    git clone $T2W_GIT_REPO ${T2W_TMP}
  fi
}

build_T2W()
{
  cd ${T2W_TMP}

  if test ${USING_EXISTENT_DIR}; then
    echo "Using T2W existent directory and respective HEAD"
  else
    if test $TAG; then
      echo "Using a clean cloned T2W directory"
      echo "Checking out $TAG (if existent, using master HEAD instead)"
      git checkout $TAG || git checkout HEAD
    fi
  fi

  T2W_REVISION=`git rev-parse HEAD | cut -c 1-8`

  echo "Revision used: ${T2W_REVISION}"

  sudo pip install -r requirements.txt

  echo "[+] Building T2W"
  POSTINST=debian/postinst
  #echo "/etc/init.d/tor2web start" >> $POSTINST
  echo "# generated by your friendly tor2web build bot :)" >> $POSTINST
  python setup.py sdist
  echo "[+] Building .deb"

  cd dist
  py2dsc tor2web-*.tar.gz
  cd deb_dist/tor2web-*
  rm -rf debian/
  cp -rf ${T2W_TMP}/debian debian

  if [ $SIGN -eq 1 ]; then
    debuild
  else
    debuild -i -us -uc -b
  fi

  mv ${T2W_TMP}/dist ${T2W_BUILD}
}

if [ $AUTOYES ]; then
  auto_setup_env
else
  interactive_setup_env
fi
build_T2W

echo "[+] All done!"
echo ""
echo "T2W build is now present in ${T2W_BUILD}"
